alias add="git add"
alias branch="git branch"
alias clone="git clone"
alias co="git checkout"
alias commit="git commit"
alias diff="git diff"
alias fetch="git fetch"
alias hist="git log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short | mate"
alias merge="git merge"
alias pull="git pull"
alias push="git push"
alias rebase="git rebase"
alias stash="git stash"
alias status="git status -sb"