"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 750

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$crystal\
$elixir\
$erlang\
$nodejs\
$ruby\
$rust\
$swift\
$cmd_duration\
$fill\
$time\
$line_break\
$container\
$character"""

[character]
error_symbol = '[●](bold red)'
success_symbol = '[●](bold green)'

[cmd_duration]
format = '\([$duration]($style)\)'
style = 'normal'

[container]
symbol = '📦'
style = 'bold blue'

[directory]
read_only = ' 🔒'
style = 'white'
truncation_symbol = '…/'

[elixir]
format = '[\(Elixir(: $version)\)]($style) '

[erlang]
format = '[\(Erlang(: $version)\)]($style) '

[fill]
symbol = '·'
style = 'bright black'

[git_branch]
always_show_remote = true
format = '[<$branch(:$remote_name/$remote_branch)>]($style) '
style = 'green'

[git_commit]
format = '[<($hash$tag)>]($style) '
style = 'green'
tag_disabled = false

[git_metrics]
added_style = 'green'
deleted_style = 'red'
disabled = false

[hostname]
format = '@ [$hostname](blue) '
ssh_only = false

[nodejs]
format = '[\(Node.js(: $version)\)]($style) '

[ruby]
format = '[\(Ruby(: $version)\)]($style) '

[rust]
format = '[\(Rust(: $version)\)]($style) '

[time]
format = ' [\[ $time \]]($style)'
disabled = false
style = 'normal'

[username]
format = '[$user]($style) '
show_always = true
style_root = 'bold yellow'
style_user = 'bold yellow'
