#!/usr/bin/env sh

# Forward arguments to GNU stow and strip spurious warning
#
# https://github.com/aspiers/stow/issues/65

#function stow() {
  command stow "${@}" 2> >(grep -v 'BUG in find_stowed_path' 1>&2)
#}
