atom__homebrew_casks:
  - name: atom

atom__config_path: "{{ home_dir }}/.atom"

atom__packages_config_path: .atom/packages.txt

atom__files:
  - name: .atom/config.cson
  - name: .atom/init.coffee
  - name: .atom/keymap.cson
  - name: "{{ atom__packages_config_path }}"
  - name: .atom/snippets.cson
  - name: .atom/styles.less
