- name: Install packages with Homebrew
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ apps__homebrew_packages }}"

- name: Install packages with Homebrew-Cask
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ apps__homebrew_cask_packages }}"

- name: Install apps with mas
  shell: "mas install {{ item.id }}"
  register: mas_install_result
  with_items: "{{ apps__mas_apps }}"
  changed_when: "' is already installed' not in mas_install_result.stdout"
