- import_tasks: ../common/tasks/homebrew.yml
  vars:
    packages: "{{ node__homebrew_packages }}"

- name: Install packages with npm
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ node__npm_packages }}"
