- import_tasks: ../common/tasks/homebrew.yml
  vars:
    packages: "{{ node__homebrew_packages }}"

- import_tasks: ../common/tasks/link-config-files.yml
  vars:
    linked_files: "{{ node__linked_files }}"

- name: Install packages with npm
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ node__npm_packages }}"
