- name: Install packages with Homebrew
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ node__homebrew_packages }}"

- name: Link config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ node__linked_files }}"

- name: Install packages with npm
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ node__npm_packages }}"
