ruby__homebrew_brews:
  - name: jgarber623/extras/rbenv-each
  - name: jgarber623/extras/rbenv-env
  - name: jgarber623/extras/rbenv-gem-update
  - name: rbenv
  - name: rbenv-aliases
  - name: rbenv-default-gems
  - name: rbenv-use
  - name: ruby-build

ruby__bundler_config_path: "{{ home_dir }}/.bundle"
ruby__rbenv_config_path: "{{ home_dir }}/.rbenv"

ruby__files:
  - name: .bundle/config
  - name: .gemrc
  - name: .irbrc
  - name: .pryrc

ruby__default_gems_config: "{{ ruby__rbenv_config_path }}/default-gems"

ruby__default_gems:
  - bundler
  - foreman
  - rails

ruby__global_version: 2.7.4

ruby__versions:
  - 3.0.2
  - "{{ ruby__global_version }}"
  - 2.6.8
  - 2.5.9
  - 2.4.10
