- name: Install packages with Homebrew-Cask
  homebrew_cask:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
  with_items: "{{ packages }}"
