mas__homebrew_packages:
  - mas

mas__packages:
  - name: 1Blocker
    id: 1107421413
  - name: Airmail 3
    id: 918858936
  - name: Bear
    id: 1091189122
  - name: Clear
    id: 504544917
  - name: Day One
    id: 1055511498
  - name: Deliveries
    id: 924726344
  - name: Fantastical 2
    id: 975937182
  - name: Icon Slate
    id: 439697913
  - name: iMovie
    id: 408981434
  - name: Keynote
    id: 409183694
  - name: Keypad
    id: 928906884
  - name: Mactracker
    id: 430255202
  - name: Marked 2
    id: 890031187
  - name: Monity
    id: 915542151
  - name: Moom
    id: 419330170
  - name: Name Mangler 3
    id: 603637384
  - name: Numbers
    id: 409203825
  - name: Pages
    id: 409201541
  - name: Patterns
    id: 429449079
  - name: Pixelmator
    id: 407963104
  - name: Reeder
    id: 880001334
  - name: Slack
    id: 803453959
  - name: StopTheMadness
    id: 1376402589
  - name: The Unarchiver
    id: 425424353
  - name: Tweetbot
    id: 1384080005
